using DevExpress.XtraEditors;
using DevExpress.XtraReports.UI;
using QLVT.SubForm;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace QLVT.ReportForm
{
    public partial class FormDanhMucVatTu : DevExpress.XtraEditors.XtraForm
    {
        public FormDanhMucVatTu()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            
        }
        private Form CheckExists(Type ftype)
        {
            foreach (Form f in this.MdiChildren)
                if (f.GetType() == ftype)
                    return f;
            return null;
        }
        private void barButtonItem1_ItemClick(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            ReportForm.ReportDanhMucVatTu report = new ReportForm.ReportDanhMucVatTu();
            ReportPrintTool printTool = new ReportPrintTool(report);
            printTool.ShowPreviewDialog();

        }


        private void button2_Click(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {
            try
            {
                ReportDanhMucVatTu report = new ReportDanhMucVatTu();

                              // Đường dẫn đến thư mục ExportReport trong dự án
                string exportFolderPath = System.IO.Path.Combine(Application.StartupPath, "ExportReport");

                // Kiểm tra xem thư mục ExportReport có tồn tại không, nếu không thì tạo nó
                if (!System.IO.Directory.Exists(exportFolderPath))
                {
                    System.IO.Directory.CreateDirectory(exportFolderPath);
                }

                string filePath = System.IO.Path.Combine(exportFolderPath, "ReportDanhMucVatTu.pdf");

                if (File.Exists(filePath))
                {
                    DialogResult dr = MessageBox.Show("File ReportDanhMucVatTu.pdf tại thư mục ExportReport đã có!\nBạn có muốn tạo lại?",
                        "Xác nhận", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                    if (dr == DialogResult.Yes)
                    {
                        report.ExportToPdf(filePath);
                        MessageBox.Show("File ReportDanhMucVatTu.pdf đã được ghi thành công tại thư mục ExportReport",
                            "Xác nhận", MessageBoxButtons.OK, MessageBoxIcon.Information);
                        string startupPath = Application.StartupPath;
                        MessageBox.Show($"Thư mục gốc của ứng dụng: {startupPath}");
                    }
                }
                else
                {
                    report.ExportToPdf(filePath);
                    MessageBox.Show("File ReportDanhMucVatTu.pdf đã được ghi thành công tại thư mục ExportReport",
                        "Xác nhận", MessageBoxButtons.OK, MessageBoxIcon.Information);
                }
            }
            catch (IOException ex)
            {
                MessageBox.Show("Vui lòng đóng file ReportDanhMucVatTu.pdf",
                    "Xác nhận", MessageBoxButtons.OKCancel, MessageBoxIcon.Warning);
                return;
            }
        }

        private void barButtonItem1_ItemClick_1(object sender, DevExpress.XtraBars.ItemClickEventArgs e)
        {

        }

        private void FormDanhMucVatTu_Load(object sender, EventArgs e)
        {
            // TODO: This line of code loads data into the 'qLVT_NHAPXUATDataSet.VATTU' table. You can move, or remove it, as needed.
            dataSet.EnforceConstraints = false;
            this.VATTUTableAdapter.Connection.ConnectionString = Program.connstr;
            this.VATTUTableAdapter.Fill(this.dataSet.VATTU);

        }
    }
}