USE [QLVT_NHAPXUAT]
GO

/****** Object:  StoredProcedure [dbo].[sp_KiemTraDDHTrongCTDDH]    Script Date: 08/11/2023 8:30:47 CH ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[sp_KiemTraDDHTrongCTDDH]
	@MADDH NVARCHAR(10)
AS
BEGIN
	IF EXISTS (SELECT 1 FROM CTDDH WHERE CTDDH.MADDH = @MADDH) RETURN 1;
	RETURN 0;
END
GO

