
CREATE VIEW [dbo].[view_DanhSachVatTu]
AS
SELECT VATTU.MAVT,
	   VATTU.TENVT,
	   LOAIVATTU.TENLVT,
	   VATTU.SLT,
	   VATTU.DVT
	   FROM DBO.VATTU, DBO.LOAIVATTU
	   WHERE LOAIVATTU.MALVT = VATTU.MALVT
GO